# Убрали version (как и просит warning)
services:
  service1:
    build: 
      context: ./service1
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network

  service2:
    build:
      context: ./service2  
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge